language: perl
perl:
    - "5.16"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
    - "cpanm Carton 2>&1 | sed -u 's/^/       /'"
install: 
    - "carton install --deployment 2>&1 | sed -u 's/^/       /'"
script:
    - "carton exec -- prove t"
